apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pgsql-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
